# Generated by Django 4.1.7 on 2023-12-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("year", models.CharField(max_length=10)),
                ("length", models.CharField(max_length=100)),
                ("poster_url", models.CharField(max_length=500)),
                ("imdb_link", models.CharField(max_length=500)),
            ],
        ),
    ]
