# Generated by Django 4.1.7 on 2023-12-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="rating",
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
