# Generated by Django 4.1.7 on 2023-12-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_movie_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="amazon_prime",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="movie",
            name="apple_tv",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="movie",
            name="disney_plus",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="movie",
            name="hbo_max",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="movie", name="hulu", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="movie",
            name="last_update",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="netflix",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="movie",
            name="peacock",
            field=models.BooleanField(default=False),
        ),
    ]
