# Generated by Django 4.2.9 on 2024-01-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_rename_imdb_link_movie_tmdb_link_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt_text", models.CharField(max_length=2000)),
                ("if_random", models.BooleanField()),
                ("response_time", models.DurationField()),
                (
                    "recommended_movies",
                    models.ManyToManyField(
                        related_name="recommendations", to="mainapp.movie"
                    ),
                ),
            ],
        ),
    ]
