# Generated by Django 4.2.9 on 2024-01-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_remove_recommendation_if_random_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendation",
            name="response_time",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
