# Generated by Django 4.2.9 on 2024-02-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0008_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="sending_time",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="category",
            field=models.CharField(
                choices=[
                    ("error", "Error/bug"),
                    ("feedback", "Feedback"),
                    ("question", "Question"),
                    ("other", "Other"),
                ],
                default="feedback",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="feedback", name="mail", field=models.EmailField(max_length=30),
        ),
    ]
