from django.core.management.base import BaseCommand
import movieposters as mp
from mainapp.models import Movie
from mainapp.views import check_platforms_for_a_movie
from datetime import datetime

class Command(BaseCommand):

    help = "Migrating databse with movies data"

    def handle(self, *args, **options):

        movies = [
        {"Title": "The Shawshank Redemption", "Year": 1994},
        {"Title": "The Godfather", "Year": 1972},
        {"Title": "The Dark Knight", "Year": 2008},
        {"Title": "Pulp Fiction", "Year": 1994},
        {"Title": "Schindler's List", "Year": 1993},
        {"Title": "The Lord of the Rings: The Return of the King", "Year": 2003},
        {"Title": "Forrest Gump", "Year": 1994},
        {"Title": "Inception", "Year": 2010},
        {"Title": "The Matrix", "Year": 1999},
        {"Title": "Fight Club", "Year": 1999},
        {"Title": "Star Wars: Episode IV - A New Hope", "Year": 1977},
        {"Title": "The Silence of the Lambs", "Year": 1991},
        {"Title": "Titanic", "Year": 1997},
        {"Title": "Casablanca", "Year": 1942},
        {"Title": "The Godfather: Part II", "Year": 1974},
        {"Title": "Gladiator", "Year": 2000},
        {"Title": "The Dark Knight Rises", "Year": 2012},
        {"Title": "The Lord of the Rings: The Fellowship of the Ring", "Year": 2001},
        {"Title": "The Matrix Reloaded", "Year": 2003},
        {"Title": "The Matrix Revolutions", "Year": 2003},
        {"Title": "The Shining", "Year": 1980},
        {"Title": "Jurassic Park", "Year": 1993},
        {"Title": "Back to the Future", "Year": 1985},
        {"Title": "E.T. the Extra-Terrestrial", "Year": 1982},
        {"Title": "The Wizard of Oz", "Year": 1939},
        {"Title": "12 Angry Men", "Year": 1957},
        {"Title": "The Lion King", "Year": 1994},
        {"Title": "Inglourious Basterds", "Year": 2009},
        {"Title": "The Departed", "Year": 2006},
        {"Title": "The Social Network", "Year": 2010},
        {"Title": "The Wolf of Wall Street", "Year": 2013},
        {"Title": "The Grand Budapest Hotel", "Year": 2014},
        {"Title": "The Revenant", "Year": 2015},
        {"Title": "Mad Max: Fury Road", "Year": 2015},
        {"Title": "La La Land", "Year": 2016},
        {"Title": "The Shape of Water", "Year": 2017},
        {"Title": "Get Out", "Year": 2017},
        {"Title": "Black Panther", "Year": 2018},
        {"Title": "Parasite", "Year": 2019},
        {"Title": "Joker", "Year": 2019},
        {"Title": "The Irishman", "Year": 2019},
        {"Title": "A Beautiful Mind", "Year": 2001},
        {"Title": "The Departed", "Year": 2006},
        {"Title": "No Country for Old Men", "Year": 2007},
        {"Title": "The Prestige", "Year": 2006},
        {"Title": "Interstellar", "Year": 2014},
        {"Title": "Dunkirk", "Year": 2017},
        {"Title": "1917", "Year": 2019},
        {"Title": "The Green Mile", "Year": 1999},
        {"Title": "The Usual Suspects", "Year": 1995},
        {"Title": "The Sixth Sense", "Year": 1999},
        {"Title": "Schindler's List", "Year": 1993},
        {"Title": "Braveheart", "Year": 1995},
        {"Title": "Saving Private Ryan", "Year": 1998},
        {"Title": "American Beauty", "Year": 1999},
        {"Title": "Gladiator", "Year": 2000},
        {"Title": "A Beautiful Mind", "Year": 2001},
        {"Title": "The Lord of the Rings: The Two Towers", "Year": 2002},
        {"Title": "Mystic River", "Year": 2003},
        {"Title": "Million Dollar Baby", "Year": 2004},
        {"Title": "The Departed", "Year": 2006},
        {"Title": "No Country for Old Men", "Year": 2007},
        {"Title": "Slumdog Millionaire", "Year": 2008},
        {"Title": "The Hurt Locker", "Year": 2008},
        {"Title": "Avatar", "Year": 2009},
        {"Title": "Inception", "Year": 2010},
        {"Title": "The King's Speech", "Year": 2010},
        {"Title": "The Artist", "Year": 2011},
        {"Title": "Argo", "Year": 2012},
        {"Title": "12 Years a Slave", "Year": 2013},
        {"Title": "Birdman or (The Unexpected Virtue of Ignorance)", "Year": 2014},
        {"Title": "Spotlight", "Year": 2015},
        {"Title": "Moonlight", "Year": 2016},
        {"Title": "The Shape of Water", "Year": 2017},
        {"Title": "Green Book", "Year": 2018},
        {"Title": "Parasite", "Year": 2019},
        {"Title": "Nomadland", "Year": 2020},
        {"Title": "The Trial of the Chicago 7", "Year": 2020},
        {"Title": "The Father", "Year": 2020},
        {"Title": "Dune", "Year": 2021},
        {"Title": "Spider-Man: No Way Home", "Year": 2021},
        {"Title": "Eternals", "Year": 2021},
        {"Title": "Shang-Chi and the Legend of the Ten Rings", "Year": 2021},
        {"Title": "Don't Look Up", "Year": 2021},
        {"Title": "The French Dispatch", "Year": 2021},
        {"Title": "House of Gucci", "Year": 2021},
        {"Title": "Licorice Pizza", "Year": 2021},
        {"Title": "Belfast", "Year": 2021},
        {"Title": "CODA", "Year": 2021},
        {"Title": "The Power of the Dog", "Year": 2021},
        {"Title": "A Quiet Place Part II", "Year": 2021},
        {"Title": "West Side Story", "Year": 2021},
        {"Title": "Last Night in Soho", "Year": 2021},
        {"Title": "Black Widow", "Year": 2021},
        {"Title": "Jungle Cruise", "Year": 2021},
        {"Title": "Cruella", "Year": 2021},
        {"Title": "The Suicide Squad", "Year": 2021},
        {"Title": "Godzilla vs. Kong", "Year": 2021},
        {"Title": "Fast & Furious 9", "Year": 2021},
        {"Title": "A Clockwork Orange", "Year": 1971},
        {"Title": "The Great Gatsby", "Year": 2013},
        {"Title": "The Big Lebowski", "Year": 1998},
        {"Title": "The Terminator", "Year": 1984},
        {"Title": "The Princess Bride", "Year": 1987},
        {"Title": "The Breakfast Club", "Year": 1985},
        {"Title": "Ferris Bueller's Day Off", "Year": 1986},
        {"Title": "Blade Runner", "Year": 1982},
        {"Title": "Apocalypse Now", "Year": 1979},
        {"Title": "Goodfellas", "Year": 1990},
        {"Title": "The Good, the Bad and the Ugly", "Year": 1966},
        {"Title": "A Fistful of Dollars", "Year": 1964},
        {"Title": "Once Upon a Time in the West", "Year": 1968},
        {"Title": "For a Few Dollars More", "Year": 1965},
        {"Title": "The Hateful Eight", "Year": 2015},
        {"Title": "Django Unchained", "Year": 2012},
        {"Title": "Reservoir Dogs", "Year": 1992},
        {"Title": "Kill Bill: Vol. 1", "Year": 2003},
        {"Title": "Kill Bill: Vol. 2", "Year": 2004},
        {"Title": "The Good, the Bad, the Weird", "Year": 2008},
        {"Title": "Oldboy", "Year": 2003},
        {"Title": "Pan's Labyrinth", "Year": 2006},
        {"Title": "The Devil's Backbone", "Year": 2001},
        {"Title": "Amélie", "Year": 2001},
        {"Title": "City of God", "Year": 2002},
        {"Title": "The Lives of Others", "Year": 2006},
        {"Title": "Das Boot", "Year": 1981},
        {"Title": "Downfall", "Year": 2004},
        {"Title": "The Pianist", "Year": 2002},
        {"Title": "Life is Beautiful", "Year": 1997},
        {"Title": "Cinema Paradiso", "Year": 1988},
        {"Title": "Seven Samurai", "Year": 1954},
        {"Title": "Rashomon", "Year": 1950},
        {"Title": "Yojimbo", "Year": 1961},
        {"Title": "Throne of Blood", "Year": 1957},
        {"Title": "The Hidden Fortress", "Year": 1958},
        {"Title": "Ran", "Year": 1985},
        {"Title": "Ikiru", "Year": 1952},
        {"Title": "High and Low", "Year": 1963},
        {"Title": "Akira", "Year": 1988},
        {"Title": "Ghost in the Shell", "Year": 1995},
        {"Title": "Princess Mononoke", "Year": 1997},
        {"Title": "Spirited Away", "Year": 2001},
        {"Title": "My Neighbor Totoro", "Year": 1988},
        {"Title": "Howl's Moving Castle", "Year": 2004},
        {"Title": "Grave of the Fireflies", "Year": 1988},
        {"Title": "Whisper of the Heart", "Year": 1995},
        {"Title": "The Wind Rises", "Year": 2013},
        {"Title": "Your Name", "Year": 2016},
        {"Title": "Paranoia Agent", "Year": 2004},
        {"Title": "Perfect Blue", "Year": 1997},
        {"Title": "Paprika", "Year": 2006},
        {"Title": "Millennium Actress", "Year": 2001},
        {"Title": "Tokyo Godfathers", "Year": 2003},
        {"Title": "Cowboy Bebop: The Movie", "Year": 2001},
        {"Title": "Akira", "Year": 1988},
        {"Title": "Neon Genesis Evangelion: The End of Evangelion", "Year": 1997},
        {"Title": "Spirited Away", "Year": 2001},
        {"Title": "Grave of the Fireflies", "Year": 1988},
        {"Title": "My Neighbor Totoro", "Year": 1988},
        {"Title": "Howl's Moving Castle", "Year": 2004},
        {"Title": "Princess Mononoke", "Year": 1997},
        {"Title": "Ghost in the Shell", "Year": 1995},
        {"Title": "Perfect Blue", "Year": 1997},
        {"Title": "Paprika", "Year": 2006},
        {"Title": "Millennium Actress", "Year": 2001},
        {"Title": "Tokyo Godfathers", "Year": 2003},
        {"Title": "Cowboy Bebop: The Movie", "Year": 2001},
        {"Title": "The Maltese Falcon", "Year": 1941},
        {"Title": "Gone with the Wind", "Year": 1939},
        {"Title": "Citizen Kane", "Year": 1941},
        {"Title": "The Wizard of Oz", "Year": 1939},
        {"Title": "It Happened One Night", "Year": 1934},
        {"Title": "The Graduate", "Year": 1967},
        {"Title": "Lawrence of Arabia", "Year": 1962},
        {"Title": "2001: A Space Odyssey", "Year": 1968},
        {"Title": "The Sound of Music", "Year": 1965},
        {"Title": "Casablanca", "Year": 1942},
        {"Title": "Gandhi", "Year": 1982},
        {"Title": "Rocky", "Year": 1976},
        {"Title": "A Clockwork Orange", "Year": 1971},
        {"Title": "Chinatown", "Year": 1974},
        {"Title": "The Godfather: Part III", "Year": 1990},
        {"Title": "The Great Dictator", "Year": 1940},
        {"Title": "The Maltese Falcon", "Year": 1941},
        {"Title": "Psycho", "Year": 1960},
        {"Title": "The Birds", "Year": 1963},
        {"Title": "North by Northwest", "Year": 1959},
        {"Title": "The Bridge on the River Kwai", "Year": 1957},
        {"Title": "The Maltese Falcon", "Year": 1941},
        {"Title": "To Kill a Mockingbird", "Year": 1962},
        {"Title": "The Exorcist", "Year": 1973},
        {"Title": "Jaws", "Year": 1975},
        {"Title": "Star Wars: Episode V - The Empire Strikes Back", "Year": 1980},
        {"Title": "Raiders of the Lost Ark", "Year": 1981},
        {"Title": "E.T. the Extra-Terrestrial", "Year": 1982},
        {"Title": "The Princess Bride", "Year": 1987},
        {"Title": "The Terminator 2: Judgment Day", "Year": 1991},
        {"Title": "Jurassic Park", "Year": 1993},
        {"Title": "The Lion King", "Year": 1994},
        {"Title": "Toy Story", "Year": 1995},
        {"Title": "The Big Lebowski", "Year": 1998},
        {"Title": "The Sixth Sense", "Year": 1999},
        {"Title": "Gladiator", "Year": 2000},
        {"Title": "Memento", "Year": 2000},
        {"Title": "The Lord of the Rings: The Two Towers", "Year": 2002},
        {"Title": "Finding Nemo", "Year": 2003},
        {"Title": "The Dark Knight Rises", "Year": 2012},
        {"Title": "Her", "Year": 2013},
        {"Title": "Whiplash", "Year": 2014},
        {"Title": "The Martian", "Year": 2015},
        {"Title": "La La Land", "Year": 2016},
        {"Title": "Blade Runner 2049", "Year": 2017},
        {"Title": "Joker", "Year": 2019},
        {"Title": "1917", "Year": 2019},
        {"Title": "Tenet", "Year": 2020},
        {"Title": "Soul", "Year": 2020},
        {"Title": "The Green Knight", "Year": 2021},
        {"Title": "Dune", "Year": 2021},
        {"Title": "Spider-Man: No Way Home", "Year": 2021},
        {"Title": "The Matrix Resurrections", "Year": 2021},
        {"Title": "Don't Look Up", "Year": 2021},
        {"Title": "The Lost City", "Year": 2022},
        {"Title": "Downton Abbey: A New Era", "Year": 2022},
        {"Title": "Turning Red", "Year": 2022},
        {"Title": "The Batman", "Year": 2022},
        {"Title": "Jurassic World: Dominion", "Year": 2022},
        {"Title": "Sonic the Hedgehog 2", "Year": 2022},
        {"Title": "Doctor Strange in the Multiverse of Madness", "Year": 2022},
        {"Title": "Thor: Love and Thunder", "Year": 2022},
        {"Title": "Black Adam", "Year": 2022},
        {"Title": "Avatar: The Way of Water", "Year": 2022},
        {"Title": "Guardians of the Galaxy Vol. 3", "Year": 2023},
        {"Title": "Fantastic Beasts: The Secrets of Dumbledore", "Year": 2022},
        {"Title": "The Flash", "Year": 2022},
        {"Title": "The Marvels", "Year": 2022},
        {"Title": "Uncharted", "Year": 2022},
        {"Title": "Morbius", "Year": 2022},
        {"Title": "Black Panther: Wakanda Forever", "Year": 2022},
        {"Title": "The Northman", "Year": 2022},
        {"Title": "Ambulance", "Year": 2022},
        {"Title": "Death on the Nile", "Year": 2022},
        {"Title": "Mission: Impossible 7", "Year": 2022},
    ]


        for movie in movies:

            try:
                movie_title = movie["Title"]  
                print(movie_title)
                db_movie = Movie.objects.filter(title=movie_title, year=movie["Year"])
                if db_movie.exists():
                    pass
                else:
                    imdb_link_and_local_poster = mp.get_imdb_link_from_title(movie_title)
                    poster_rating_length = mp.get_poster_from_imdb_link(imdb_link_and_local_poster[0])
                    poster_link = poster_rating_length[0]
                    rating = poster_rating_length[1]
                    length = poster_rating_length[2]
                    streaming_platforms = check_platforms_for_a_movie(movie_title, movie["Year"])
                    new_db_movie = Movie(title=movie_title, year=movie["Year"], length=length, poster_url = poster_link, imdb_link=imdb_link_and_local_poster[0], rating=rating, netflix = streaming_platforms[0], amazon_prime= streaming_platforms[1], hulu= streaming_platforms[2], disney_plus= streaming_platforms[3], hbo_max= streaming_platforms[4], apple_tv= streaming_platforms[5], peacock= streaming_platforms[6], last_update=datetime.today().date())
                    new_db_movie.save()
            except:
                print(f"Error{movie}")
        
